import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
} from "react-icons/ai";
import { FaFacebook, FaGithub, FaTwitter, FaLinkedin } from "react-icons/fa";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/design.gif";
import web2 from "../public/github.png";
import web3 from "../public/cryptoTrack.gif";
import web4 from "../public/calculator.gif";
import web5 from "../public/web5.png";
import pp1 from "../public/gfg.png";
import pp2 from "../public/leetcode.png";
import pp3 from "../public/codechef.png";

import contactus from "../public/contact-us.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-5 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyrt</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Ravi Tripathi
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi there, My name is Ravi Tripathi. I'm an Engineering Student
              whose passion is to develop project & to learn new technologies.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillInstagram />
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <div className="py-4">
              <h3 className="text-3xl py-1 dark:text-white ">
                Programming Profile
              </h3>
            </div>

            <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 ">
              <a href="https://auth.geeksforgeeks.org/user/ravitripathi1203/practice/">
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid justify-center items-center">
                    <div className="m-auto justify-center items-center">
                      <Image src={pp1} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center px-10">
                      <h3>GeeksForGeeks</h3>
                    </div>
                  </div>
                </div>
              </a>
              <a href="https://leetcode.com/ravi_tripathi98/">
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid justify-center items-center">
                    <div className="m-auto justify-center items-center">
                      <Image src={pp2} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>Leetcode</h3>
                    </div>
                  </div>
                </div>
              </a>
              <a href="https://www.codechef.com/users/ravi98iii">
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid justify-center items-center">
                    <div className="m-auto justify-center items-center">
                      <Image src={pp3} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>CodeChef</h3>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
          <div id="skills" className="py-10 p-2">
            <div className="max-w mx-auto flex flex-col justify-center h-full">
              <p className="text-xl tracking-widest uppercase text-[#5651e5]">
                Skills
              </p>
              <h2 className="py-4 dark:text-white">What I Can Do</h2>
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 ">
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>HTML</h3>
                    </div>
                  </div>
                </div>
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>CSS</h3>
                    </div>
                  </div>
                </div>
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>JavaScript</h3>
                    </div>
                  </div>
                </div>
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>React</h3>
                    </div>
                  </div>
                </div>
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>Tailwind</h3>
                    </div>
                  </div>
                </div>
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>Firebase</h3>
                    </div>
                  </div>
                </div>
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>Github</h3>
                    </div>
                  </div>
                </div>
                <div className="p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300 dark:bg-white">
                  <div className="grid grid-cols-2 gap-4 justify-center items-center">
                    <div className="m-auto">
                      <Image src={code} width="64px" height="64px" alt="/" />
                    </div>
                    <div className="flex flex-col items-center justify-center">
                      <h3>Next</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              {/* Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use. */}
              Check out some of my work right here.
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="flex flex-col  lg:flex-row lg:flex-wrap basis-1/3 flex-1">
            <div className=" mx-auto grid md:grid-cols-2 gap-8">
              <a href="https://github.com/ravitripathi02/book_recommender" className="py-4">
                <div className="cursor-pointer group shadow-md shadow-gray-600 overflow-hidden rounded-md bg-blend-overlay">
                  <Image
                    src={web1}
                    alt="random"
                    className="rounded-md duration-200 hover:scale-105"
                  />
                  <h2 className="text-center text-base capitalize my-4 font-light duration-200 group-hover:underline underline-offset-4 dark:text-gray-200">
                    <h3>Pustake- A Book Recommender</h3>
                  </h2>
                </div>
              </a>
              <a href="https://ravitripathi02.github.io/githubprofilefinder/one.html" className="py-4">
                <div className="cursor-pointer group shadow-md shadow-gray-600 overflow-hidden rounded-md bg-blend-overlay ">
                  <Image
                    src={web2}
                    alt="random"
                    className="rounded-md duration-200 hover:scale-105"
                  />
                  <h2 className="text-center text-base capitalize my-4 font-light duration-200 group-hover:underline underline-offset-4 dark:text-gray-200">
                    Git-Hub Profile Finder
                  </h2>
                </div>
              </a>
            </div>
            <div className=" mx-auto grid md:grid-cols-2 gap-8">
              <a href="https://github.com/ravitripathi02/cryptotrack" className="py-4">
                <div className="cursor-pointer group shadow-md shadow-gray-600 overflow-hidden rounded-md bg-blend-overlay">
                  <Image
                    src={web3}
                    alt="random"
                    className="rounded-md duration-200 hover:scale-105"
                  />
                  <h2 className="text-center text-base capitalize my-4 font-light duration-200 group-hover:underline underline-offset-4 dark:text-gray-200">
                    CryptoTrack- Tracker of all Digital Coins
                  </h2>
                </div>
              </a>
              <a
                href="https://ravitripathi02.github.io/calculator/calculator.html"
                className="py-4"
              >
                <div className="cursor-pointer group shadow-md shadow-gray-600 overflow-hidden rounded-md bg-blend-overlay">
                  <Image
                    src={web4}
                    alt="random"
                    className="rounded-md duration-200 hover:scale-105"
                  />
                  <h2 className="text-center text-base capitalize my-4 font-light duration-200 group-hover:underline underline-offset-4 dark:text-gray-200">
                    Voice Based Calculator
                  </h2>
                </div>
              </a>
            </div>
            <div className=" mx-auto grid md:grid-cols-2 gap-8">
              <a href="#" className="py-4">
                <div className="cursor-pointer group shadow-md shadow-gray-600 overflow-hidden rounded-md bg-blend-overlay">
                  <Image
                    src={web5}
                    alt="random"
                    className="rounded-md duration-200 hover:scale-105"
                  />
                  <h2 className="text-center text-base capitalize my-4 font-light duration-200 group-hover:underline underline-offset-4 dark:text-gray-200">
                    One
                  </h2>
                </div>
              </a>
              <a href="#" className="py-4">
                <div className="cursor-pointer group shadow-md shadow-gray-600 overflow-hidden rounded-md bg-blend-overlay">
                  <Image
                    src={web5}
                    alt="random"
                    className="rounded-md duration-200 hover:scale-105"
                  />
                  <h2 className="text-center text-base capitalize my-4 font-light duration-200 group-hover:underline underline-offset-4 dark:text-gray-200">
                    One
                  </h2>
                </div>
              </a>
            </div>
          </div>
        </section>
        <section>
          <div className="w-full ">
            <div className="max-w-screen-xl mx-auto py-16 text-center md:text-left">
              <h2 className="text-5xl md:text-7xl tracking-wider uppercase text-center text-[#5651e5] font-bold">
                contact
              </h2>

              <div className="flex flex-col md:flex-row gap-8 shadow-xl shadow-gray-600 dark:bg-gray-900 mt-4 dark:text-gray-200">
                <div className="w-full md:w-1/2 h-full rounded-xl p-4">
                  <Image
                    src={contactus}
                    alt="man with laptop"
                    className="rounded-xl"
                  />
                  <p className="font-burtons pt-2 pb-8 text-3xl py-1 dark:text-white">
                    Wants to get in touch with me.....{" "}
                  </p>

                  <div className="grid grid-cols-2 mx-auto w-4/5 gap-10">
                    <div className="flex items-center justify-center rounded-full shadow-md shadow-gray-600 hover:scale-105 duration-200 p-3 cursor-pointer">
                      <FaLinkedin size={25} />
                    </div>
                    <div className="flex items-center justify-center rounded-full shadow-md shadow-gray-600 hover:scale-105 duration-200 p-3 cursor-pointer">
                      <FaTwitter size={25} />
                    </div>
                    <div className="flex items-center justify-center rounded-full shadow-md shadow-gray-600 hover:scale-105 duration-200 p-3 cursor-pointer">
                      <FaFacebook size={25} />
                    </div>
                    <div className="flex items-center justify-center rounded-full shadow-md shadow-gray-600 hover:scale-105 duration-200 p-3 cursor-pointer">
                      <FaGithub size={25} />
                    </div>
                  </div>
                </div>

                {/* form stuff  */}
                <div className="w-full md:w-1/2 h-full rounded-xl p-4">
                  <div className="p-4 text-left">
                    <form
                      action="https://getform.io/f/357378e6-dce8-451c-8d15-226c219dc76a"
                      method="POST"
                    >
                      <div className="grid grid-cols-2 gap-4 w-full py-2">
                        <div className="flex flex-col">
                          <label className="capitalize text-sm py-2 text-slate-600 font-light dark:text-gray-200">
                            name
                          </label>
                          <input
                            type="text"
                            name="name"
                            className="border-2 rounded-lg p-3 flex focus:outline-none border-blue-200"
                          />
                        </div>
                        <div className="flex flex-col">
                          <label className="capitalize text-sm py-2 text-slate-600 font-light dark:text-gray-200">
                            phone
                          </label>
                          <input
                            type="text"
                            name="phone"
                            className="border-2 rounded-lg p-3 flex focus:outline-none border-blue-200"
                          />
                        </div>

                        <div className="flex flex-col col-span-2">
                          <label className="capitalize text-sm py-2 text-slate-600 font-light dark:text-gray-200">
                            email
                          </label>
                          <input
                            type="email"
                            name="email"
                            className="border-2 rounded-lg p-3 flex focus:outline-none border-blue-200"
                          />
                        </div>
                        <div className="flex flex-col col-span-2">
                          <label className="capitalize text-sm py-2 text-slate-600 font-light dark:text-gray-200">
                            message
                          </label>
                          <textarea
                            name="message"
                            rows="10"
                            className="border-2 rounded-lg p-3 flex focus:outline-none border-blue-200"
                          ></textarea>
                        </div>
                      </div>

                      <div className="flex items-center justify-center">
                        <button className="my-8 bg-blue-500 text-white px-6 py-3 font-bold uppercase rounded-md tracking-wider cursor-pointer hover:scale-105 duration-200">
                          send message
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
